# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

config: &config
  docker:
    # specify the version you desire here
    # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
    - image: circleci/python:3.6.8
  
  working_directory: ~/repo

jobs:

  setup:
    <<: *config

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements/requirements.txt" }}-{{ checksum "requirements/test.txt" }}
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -r requirements/requirements.txt
            pip install -r requirements/test.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements/requirements.txt" }}-{{ checksum "requirements/test.txt" }}

      - persist_to_workspace:
          root: .
          paths:
            - venv

  unit:
    <<: *config

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest tests/
            coverage report --fail-under=100

      - store_artifacts:
          path: htmlcov/
          destination: test-reports

  build:
    <<: *config

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install wheel
            python setup.py bdist_wheel
            md5sum dist/cvp_ommqtt-0.2.1-py3-none-any.whl

  lint:
    <<: *config

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make lint

      - store_artifacts:
          path: htmlcov/
          destination: test-reports
  
  system_tests:
    <<: *config

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      
      - run:
          name: install dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -y mosquitto mosquitto-clients

      - run:
          name: run mosquitto
          background: true
          command: |
            mosquitto

      - run:
          name: run mosquitto listener
          background: true
          command: |
            sleep 2
            mosquitto_sub -t "#" -v > mosquitto.txt

      - run:
          name: run ommqtt tests
          command: |
            sleep 5
            . venv/bin/activate
            make run_ommqtt_system_tests
            sleep 1
            make check_ommqtt_system_tests

workflows:
  version: 2
  test_unit_and_system:
    jobs:
      - setup
      - unit : { requires: [setup] }
      - lint : { requires: [setup] }
      - build  : { requires: [setup] }
      - system_tests : { requires: [setup] }
